spring.application.name=odin
spring.datasource.url=jdbc:mysql://localhost:3306/odin
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
